### ISSUE TITLE
Bug caused by inverse powers of 10

### ISSUE THREAD

**Issue by mw8** [jverzani/SymPy.jl#23]
Here is a minimal example:

    using SymPy
    x = Sym("x");
    solve(0.00000001*x, x)

Which gives the output on Juliabox:

    BoundsError()
    while loading In[1], in expression starting on line 3

    in solve at /home/juser/.julia/v0.3/SymPy/src/math.jl:287

I think what is happening is that 0.00000001 gets simplified first to 10^(-8), but 10^(-8) is later evaluated by trying to invert the integer 10, which causes the bounds error.

Also, notice that changing the constant to 0.0000001 (which is 10^(-7)) gives no error

**Comment by jverzani** [comment]
Thanks for reporting this. It is odd. On my Mac it craps out on `solve(1e-32*x, x)`. 

Seems like a power of 2 thing. Doubt I can do anything to work around it, as I think it sits in the python code, as this seems to show (on JuliaBox)

```
using PyCall
@pyimport sympy

x = sympy.symbols("x")

y7 = pyeval("x*y", x=x, y=1e-7)
y8 = pyeval("x*y", x=x, y=1e-8)
sympy.solve(y7), sympy.solve(y8)
```

And then try this: http://www.sympygamma.com/input/?i=solve%281e-32*x%29 (as compared to 31).

**Comment by mw8** [comment]
Your code example also shows that it doesn't work for any power of 10 less than -8, so it's not just power of 2 weirdness.
