### ISSUE TITLE
Latest SymPy fails to load with latest Julia v0.4

### ISSUE THREAD

**Issue by jzuhone** [jverzani/SymPy.jl#24]
Attempting to load the latest SymPy version in the latest Julia v0.4 source results in this:
```julia
julia> using SymPy
ERROR: LoadError: UndefVarError: @document not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /Users/jzuhone/.julia/v0.4/SymPy/src/SymPy.jl, in expression starting on line 26
```

**Comment by jzuhone** [comment]
The issue appears to be caused by the fact that the `@document` macro is not defined unless `Docile` is loaded, but the file has this:

```julia
## * Docile is used for documentation
if VERSION < v"0.4.0-dev"
    using Docile
end
@document
```

Is this the correct fix, in your judgment?

```julia
## * Docile is used for documentation
if VERSION < v"0.4.0-dev"
    using Docile
    @document
end
```

**Comment by jverzani** [comment]
Thanks! I tried your idea and it didn't work. Instead it seems that this does:


```
if VERSION < v"0.4.0-dev"
    using Docile
else
    macro document() nothing end    
end
@document
```

(Which of course is only temporary until the docstrings part of Docile works its way into base.)

If this works, can you let me know and I'll push the change to METADATA?

**Comment by jzuhone** [comment]
@jverzani Yep, looks good to go! Thanks!

**Comment by jverzani** [comment]
Great, thanks for letting me know.

On Mon, Feb 2, 2015 at 10:45 AM, John ZuHone <notifications@github.com>
wrote:

> @jverzani <https://github.com/jverzani> Yep, looks good to go! Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/24#issuecomment-72478856>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu
