### ISSUE TITLE
Dictionary pretty printing

### ISSUE THREAD

**Issue by schmrlng** [jverzani/SymPy.jl#28]
The function `writemime(io::IO, ::MIME"text/latex", d::Dict)` in display.jl overrides the default Base implementation for showing dictionaries in IJulia. Presumably this is by design for some feature of SymPy.jl, but things can get pretty messy when you're using the package in conjunction with dictionaries from other sources, e.g. when working with JSON-blob-style dictionaries of nested data structures, or even something flat like `{"longarray" => [1:10000]}` that has a long full representation. Perhaps the `Latex` default in `writemime(io::IO, ::MIME"text/latex", d::Dict)`:
```
Latex(x) = string(x)
```
might be safer as
 ```
Latex(x) = sprint(Base.showlimited, x)
```
Or is dictionary pretty printing truly necessary for inclusion in SymPy.jl?

**Comment by jverzani** [comment]
Thanks for the suggestion. Pretty printing isn't necessary, but I do like it. If this change (e72e73287e40778566b8d81522760eba911a2c3b) isn't sufficient, let me know and I'll revisit.
