### ISSUE TITLE
`at_syms` instead of `at_vars`?

### ISSUE THREAD

**Issue by jverzani** [jverzani/SymPy.jl#34]
The macros syms and vars are similar, only vars assigns to values in the main workspace, whereas syms uses local assignment. MATLAB has a "syms" like macro that works like "vars". Perhaps the two should be renamed? Or should the current "syms" behaviour be retired? The `symbols` function does the same thing.

**Comment by dhoegh** [comment]
I have been tripped by the fact that `syms` in Matlab behave as `@vars`. So it seems reasonable to make `@syms`  to behave as `@vars`. In addition `@syms` is now equivalent and only marginally shorter than the function equivalent and using the function version is less magic as a macro can do anything.
```
x,y = @syms x, y
x, y = symbols("x, y")
```

**Comment by jverzani** [comment]
Okay, I bit the bullet here (4c9eb9c). `@syms` is the same as `@vars` and `@osyms` takes the role that `@syms` played. In time `@vars` should be phased out, and then `@osyms` will be renamed or dropped. Thanks for the feedback.
