### ISSUE TITLE
automate sympy installation with Conda

### ISSUE THREAD

**Issue by stevengj** [jverzani/SymPy.jl#36]
Now that PyCall (1.1 or later) supports using the Conda.jl Python distribution, you should be able to do something like https://github.com/stevengj/PyPlot.jl/commit/7169a21e7e39e422e4e5f79da18dd2bfd5e7a8a1 to automate installation of `sympy` in `__init__` when `PyCall.conda` is `true`.

**Comment by jverzani** [comment]
That's awesome. Thanks for pointing this out.

**Comment by jverzani** [comment]
This is closed by #39
