### ISSUE TITLE
Plots is imported but is not REQUIREd

### ISSUE THREAD

**Issue by stevengj** [jverzani/SymPy.jl#37]
Using the `master` version of SymPy, https://github.com/jverzani/SymPy.jl/blob/199e021d5084a468c6bee79bad164a79ba43f229/src/SymPy.jl#L44 calls `using Plots` in 0.4, but the Plots package is not in the REQUIRE file, leading to a LoadError in a fresh install.

**Comment by jverzani** [comment]
Thanks for letting me know. Will address before tagging a new version.

**Comment by jverzani** [comment]
Closed now with 636655aaea00b17f042d04256c24e69265203bae. Thanks again.
