### ISSUE TITLE
ERROR: type Plot has no field initargs

### ISSUE THREAD

**Issue by jagot** [jverzani/SymPy.jl#46]
When trying the example in the tutorial
```julia
using SymPy
x = symbols("x")
using Plots
backend(:gadfly)
plot(x^2 - 2, -2,2)
```
I get this error
```
ERROR: type Plot has no field initargs
 in createKWargsList at ~/.julia/v0.4/SymPy/src/plot.jl:273
 in plot! at ~/.julia/v0.4/Plots/src/plot.jl:93
 in plot at ~/.julia/v0.4/Plots/src/plot.jl:56
```

This is probably due to the fact that `initargs` was renamed to `plotargs` in tbreloff/Plots.jl@6236acea02c5418c244b8ad590d593ffc3a02da7

Changing `initargs` to `plotargs` in [plot.jl#L274](https://github.com/jverzani/SymPy.jl/blob/master/src/plot.jl#L274), gives a new error, however:
```
[Plots.jl] Initializing backend: gadfly
ERROR: PyError (:PyEval_EvalCode) <class 'NameError'>
NameError("name 'fn' is not defined",)
  File "PyCall.jl", line 1, in <module>
  File "PyCall.jl", line 1, in <listcomp>

 [inlined code] from ~/.julia/v0.4/PyCall/src/exception.jl:81
 in pyeval_ at ~/.julia/v0.4/PyCall/src/PyCall.jl:534
 in pyeval at ~/.julia/v0.4/PyCall/src/PyCall.jl:558
 in pyeval at ~/.julia/v0.4/PyCall/src/PyCall.jl:555
 in mapsubs at ~/.julia/v0.4/SymPy/src/plot.jl:299
 in computeXandY at ~/.julia/v0.4/Plots/src/plot.jl:251
 in createKWargsList at ~/.julia/v0.4/Plots/src/plot.jl:286
 in createKWargsList at ~/.julia/v0.4/SymPy/src/plot.jl:275
 in plot! at ~/.julia/v0.4/Plots/src/plot.jl:93
 in plot at ~/.julia/v0.4/Plots/src/plot.jl:56
```

**Comment by jverzani** [comment]
Many thanks for this! I checked in the first change with 4139751. I don't get the next error. This comes from calling `pyeval`. Can you check that it still happens after the change? I'm not sure how to debug at the moment and am hoping it was a transient issue... If it proves hard to do, I can use a slower fallback

**Comment by jverzani** [comment]
Okay, decided to leave in a fallback incase something goes wrong. Hopefully with d097499 this will be all fixed for you. If not, please reopen. Thanks for the report!
