### ISSUE TITLE
nsolve conversion to Float64

### ISSUE THREAD

**Issue by pabloferz** [jverzani/SymPy.jl#48]
Before anything else thanks @jverzani for this package I really like the effort.

I was trying to use `nsolve` yesterday and found that for different starting points, there three different errors thrown. Two of them seemed normal as they were SymPy errors of convergence and division by zero, but the other one was a Julia's `InexactError`. By looking at your code I found that you are doing conversions to `Float64` (I imagine for type stability reasons).

The problem is that in some cases `nsolve` returns a `Complex`, and in many of those cases, the imaginary part is extremely small. But your code is trying to do the conversion anyway. This actually was impeding me to find a root in an interval.

I used the following code to workaround that

```julia
function nsolve(ex::Sym, x0::Number)
    α = sympy_meth(:nsolve, project(ex). x0)
    typeof(α) <: Complex && imag(α) < eps() && return convert(Float64, real(α))
    return convert(Float64, α)
end
```

I think there might be other alternatives. One of them is restructure `SymPy.jl`'s `nsolve` so it you can define the return type to be `Complex`. Another one would be to look at the SymPy code, rewrite it in Julia in a way that is type stable, as far as I understand SymPy uses `mpmath.findroot` to find roots. But for now I'm using the code above.

I do not have to much time to do those changes by my own, but I sure can help.

**Comment by jverzani** [comment]
Thanks for pointing this out! That function was written before I defined `N` to do basically what you are doing here. So the return value is now (with bac241a) just a symbolic number or vector. Calling `N` on either will convert to a floating point or complex number.

**Comment by pabloferz** [comment]
I see. Thanks again for the package!
