### ISSUE TITLE
Function coeffs not found

### ISSUE THREAD

**Issue by baggepinnen** [jverzani/SymPy.jl#58]
The following is a short snippet which I think sould work, but doesn't

```julia
a = Sym("a")
coeffs(a^2+a,a)
```

with output
```julia
julia> a = Sym("a")
a

julia> coeffs(a^2+a,a)
ERROR: KeyError: coeffs not found
 in getindex at /local/home/fredrikb/.julia/v0.4/PyCall/src/PyCall.jl:239
 in object_meth at /local/home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:279
 in coeffs at /local/home/fredrikb/.julia/v0.4/SymPy/src/SymPy.jl:205
```

```
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34* (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
  sympy-0.7.6.1
```

**Comment by jverzani** [comment]
In SymPy `coeffs` is a method of `Polynomials`, not general expression, so you can try:

```
p = Poly(a^2 + a, a)
coeffs(p)
```

**Comment by jverzani** [comment]
I should have pointed you to the coefficients section of http://nbviewer.jupyter.org/github/jverzani/SymPy.jl/blob/master/examples/tutorial.ipynb

It has a bit of detail.

**Comment by baggepinnen** [comment]
Thanks for the tip, what I really wanted was the function `coeff`not `coeffs`!
I sometimes find the error messages from SymPy a bit different from normal Julia error messages, I would have expected something in line with 
```julia
ERROR: MethodError: `coeffs` has no method matching coeffs(::Sym, ::Sym)
```

**Comment by jverzani** [comment]
Yeah, the error messages could be more transparent. This one arises, as we look up the symbol `coeffs` in a few places (the sympy module, then from Python object's methods...) Not sure I can do much here except wrap things in try/catch.
