### ISSUE TITLE
SymPy.Sym to julia method

### ISSUE THREAD

**Issue by pabloferz** [jverzani/SymPy.jl#60]
Hi, this is not really an issue but more of a feature request. I was thinking the other day that some might want to use the result of a symbolic computation to define a function in julia.

I shouldn't be to hard (for simple expressions) to convert the string to a julia function (probably making some string substitution and using `eval`). I don't know it this seem reasonable and I'm aware that in some cases it won't work out of the box but I wanted to open the issue you to fiddle around with the idea.

**Comment by jverzani** [comment]
There is a convert method for expressions into functions. So basically `x*y*z` becomes `(x,y,z) -> x*y*z`. The order of the variables comes from `free_symbols`. Is there anything else that might be useful to add?

**Comment by pabloferz** [comment]
As far as I can see `convert(Function, f::Sym)` seems to return something like

```julia
(x::Sym,y::Sym,z::Sym) -> x*y*z
```

I was thinking instead on a way to define the function `f(x::Number, y::Number, z::Number) = x*y*z` from the SymPy expression. Probably even something like `exp(-IM*PI*x)*sin(PI*x)`, where `x::Sym`, and convert it to `f(x::Number) = exp(-im*π*x) * sin(π*x)`.

I guess it is probably too much, but the scenario I had in mind was doing some sort of symbolic calculation for a function, get another function in return, translate the result to a julia function using SymPy and use the final julia method for some fast calculations.

Just to be clear, I just wanted to discuss the posibility of implementing something of the sort. If it turns in the end to be a real pain to have anything like, we can close the issue.

**Comment by jverzani** [comment]
No, that isn't quite right. The convert(Function, x*y*z) doesn't require the inputs to be symbolic, they can be numbers. The output is symbolic though. However, you can compose with the `N` function to get what you want: `pablos_fn(ex::Sym) = (args...) -> N(convert(Function, ex)(args...))`. (Or if you know the output type, convert it directly and bypass `N` which is not type stable.)

But, as you know, that isn't going to be fast. In SymPy itself you can "lambdify" functions which is really what you are asking for here-- creating a function that bypasses the trip to SymPy and back. For that, I'd have to see how the expression is stored in SymPy. Maybe there is a simple enough way to translate that into `Julia` code.

**Comment by jverzani** [comment]
Seems like this page http://docs.sympy.org/dev/tutorial/manipulation.html gives some direction as to how this could be done. Something to think about....

**Comment by asmeurer** [comment]
It would be nice to see a SymPy -> Julia code generator implemented in SymPy itself (SymPy can already generate code for other languages like C, Fortran, and Matlab).

**Comment by pabloferz** [comment]
Yeah, that would be great. I guess that given the infrastructure already in place shouldn't be to hard to write one. Maybe also a code generator that generates it in form of a Julia's `Expr`.

**Comment by jverzani** [comment]
This would be great @asmeurer ! In the meantime, @pabloferz something hacky like this could be extended:

```

_func(x) = (x.x)[:func]
_funcname(x) = _func(x)[:__name__]
_args(x) = (x.x)[:args]
_srepr(x) = sympy_meth(:srepr, x)

val_map = Dict(
               "NegativeOne" => :(-1),
               "Pi" => :pi,
               "Exp1" => :e,
               "Infinity" => :Inf,
               "NegativeInfinity" => :(-Inf),
               "ImaginaryUnit" => :im
               )
fn_map = Dict(
              "Add" => :+,
              "Sub" => :-,
              "Mul" => :*,
              "Div" => :/,
              "Pow" => :^,
              "sin" => :sin,
              "cos" => :cos,
              "tan" => :tan,
              "exp" => :exp,
              "log" => :log,
              )
              
              

function walk_expression(ex, domap=true)

    fn = _funcname(ex)
    
    if fn == "Symbol"
        return symbol(string(ex))
    elseif fn in ["Integer" , "Float"]
        return N(ex)
    elseif haskey(val_map, fn)
        return val_map[fn]
    end

    as = _args(ex)
    if domap
        return Expr(:call, fn_map[fn], [walk_expression(a, domap) for a in as]...)
    else
        return tuple(fn, [walk_expression(a, domap) for a in as]...)
    end
end


function lambdify(ex::Sym)
    eval(Expr(:function,
              Expr(:call, gensym(), map(symbol,free_symbols(ex))...),
              walk_expression(ex)))
end
```

**Comment by pabloferz** [comment]
Yeah, I was thinking in writing something similar. I guess it is just a matter of writing the `Dict` with as most equivalences as possible.

**Comment by asmeurer** [comment]
I've only dabbled in Julia so far, so I'm probably not the best person to write it, but pull requests are welcome. It should be easy to write a JuliaCodePrinter assuming you know all the right Julia function conversions.  That would generate a Julia expression (string) for a SymPy expression. It would then assumedly be easy for SymPy.jl or anyone else for that matter to take that and wrap it in a Julia function (with a type signature and whatnot).  There's also improvements happening in SymPy now that would allow writing code printers in SymPy to generate the full Julia code, including the function definitions (see https://github.com/sympy/sympy/pull/10486 if you are interested in that).

**Comment by jverzani** [comment]
I pushed the hack for `lambdify` with e0a8985 . When I find time, I'll look into the sympy issue 10486.

**Comment by asmeurer** [comment]
The SymPy issue sympy/sympy#10486 is still a work in progress. Just letting you know about it since here will likely be interested in the project.

**Comment by pabloferz** [comment]
The partial solution works for me now. But I can give it a go and implement `JuliaCodePrinter` over sympy.

**Comment by pabloferz** [comment]
Now that https://github.com/sympy/sympy/pull/10556 is merged future versions of SymPy.jl's lambdify can leverage SymPy's new `julia_code` for example.

**Comment by jverzani** [comment]
I'm curious which will be faster. I don't really have a system where I can experiment with the underlying sympy setup. Can you benchmark? The alternative if the current lamdify is faster would be to make a print call to generate the expression, like jprint and not eval this into a function, but leave that as an option for a user. I'm pretty sure your work is more general.

**Comment by jverzani** [comment]
With 362d0ff I added support for `julia_code`, when present. Can you test? Thanks for doing this!
