### ISSUE TITLE
Solve ode with initial conditions

### ISSUE THREAD

**Issue by jmarcellopereira** [jverzani/SymPy.jl#61]
I want to solve an ode with initial conditions. For example
using SymPy
f   = SymFunction("f")
x,y = Sym("x,y")

edo1 = SymPy.diff(f(x),x) + x

SymPy.dsolve(edo1)

f(x) == C1 - x^2/2

How to solve C1 using ics option?
dsolve(eq, func=None, hint='default', simplify=True, ics=None, xi=None, eta=None, x0=0, n=6, **kwargs)

Erro:
WARNING: deprecated syntax "{a,b, ...}" at In[18]:1.
Use "Any[a,b, ...]" instead.

**Comment by jverzani** [comment]
Well, as mentioned, the `ics` argument is a bit limited. While we are willing to entertain limited solutions, here is something I could add to augment the `dsolve` of  `SymPy`. I don't know if I like the syntax. Any thoughts?

```

## Solve an initial value ODE
type IVPSolution <: SymPy.SymbolicObject
    u::PyCall.PyObject
    n::Int
end
Base.display(x::IVPSolution) = println("sym funct")
function Base.call(u::IVPSolution, x) 
    if u.n == 0
        u.u(SymPy.project(x))
    else
        __x = Sym("__x")
        diff(u.u(__x.x), __x, u.n)(x)
    end
end

function IVPSolution{T<:AbstractString}(x::T)
    u = sympy[:Function](x)
    IVPSolution(u, 0)
end

function Base.ctranspose(x::IVPSolution)
    IVPSolution(x.u, x.n + 1)
end

IVPsolve(eqn::Sym) = dsolve(eqn)

"""

Solve an intial value problem

* `eqn` the equation. Can be written as `u'(x) - u(x)` where `u` is of type `IVPSolution`
* `var` the variable of the equation. Typically `free_symbols(x)[1]`, but still, for now, is specified
* `args::Tuple...` Specification of initial values in style of `(u, x0, y0)` or `(u', x0, y0)`.

"""
function IVPsolve(eqn, var::Sym, args::Tuple...)
    out = dsolve(eqn)
    eqns = Sym[rhs(diff(out, var, f.n))(var=>x0) - y0 for (f, x0, y0) in args]
    
    out([k=>v for (k,v) in solve(eqns)]...)
end


## Examples:

using SymPy
u = IVPSolution("u")
@vars x
IVPsolve(u'(x) - 2u(x)) # same as `dsolve`: C_1 e^(2x)
IVPsolve(u'(x) - 2u(x), x, (u, 0 , 1)) # e^(2x)
IVPsolve(u''(x) - 2u(x), x, (u, 0, 1), (u', 0, 2))  ## some expression


```

**Comment by jverzani** [comment]
I went ahead an added this with 915e401 though some names were changed. I'm not sure these new names (`IVPSolution` to define a possible solution, and `ivpsolve` to solve with initial conditions) are the best possible. If you have suggestions for alternates, please comment.

**Comment by jverzani** [comment]
With dd3aaa6, the interface changed (for the better). By deprecating the call `dsolve(eqn, f(x))`, we can use `dsolve` in stead of `ivpsolve`. As well, changing `SymFunction` makes this as easy now as (for v"0.4"+):

```
u = SymFunction("u")
x = symbols("x")
dsolve(u''(x) - 2u(x), x, (u, 0, 1), (u', 0, 1))
```
