### ISSUE TITLE
`@vars` with "gamma", "beta"

### ISSUE THREAD

**Issue by jverzani** [jverzani/SymPy.jl#62]
This is odd, they make pyobjects, but they are not symbolic.

**Comment by pabloferz** [comment]
You could rewrite the macro as

```julia
macro vars(x...)
    q=Expr(:block)
    if length(x) == 1 && isa(x[1],Expr)
        @assert x[1].head === :tuple "@vars expected a list of symbols"
        x = x[1].args
    end
    for s in x
        @assert isa(s,Symbol) "@vars expected a list of symbols"
        push!(q.args, Expr(:(=), s, Expr(:call, :symbols, Expr(:quote, string(s)))))
    end
    push!(q.args, Expr(:tuple, x...))
    eval(Main, q)
end
```

gamma would be displayed as `γ` but `jprint(gamma) == "gamma"`. I think that would be OK.

**Comment by pabloferz** [comment]
Or maybe even

```julia
macro vars(x...)
    q=Expr(:block)
    if length(x) == 1 && isa(x[1],Expr)
        @assert x[1].head === :tuple "@vars expected a list of symbols"
        x = x[1].args
    end
    s = ""
    for _ in x
        @assert isa(_,Symbol) "@vars expected a list of symbols"
        s *= string(_, " ")
    end
    push!(q.args, Expr(:(=), Expr(:tuple, x...), Expr(:call, :symbols, Expr(:quote, s))))
    eval(Main, q)
end
```

**Comment by jverzani** [comment]
Thanks! Will use the first one.

On Tue, Feb 9, 2016 at 12:46 PM, Pablo Zubieta <notifications@github.com>
wrote:

> You could rewrite the macro as
>
> macro vars(x...)
>     q=Expr(:block)
>     if length(x) == 1 && isa(x[1],Expr)
>         @assert x[1].head === :tuple "@vars expected a list of symbols"
>         x = x[1].args
>     end
>     for s in x
>         @assert isa(s,Symbol) "@vars expected a list of symbols"
>         push!(q.args, Expr(:(=), s, Expr(:call, :symbols, Expr(:quote, string(s)))))
>     end
>     push!(q.args, Expr(:tuple, x...))
>     eval(Main, q)end
>
> gamma would be displayed as γ but jprint(gamma) == "gamma". I think that
> would be OK.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/62#issuecomment-181977829>.
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by pabloferz** [comment]
No problem!
