### ISSUE TITLE
julia v0.5 incompatibility

### ISSUE THREAD

**Issue by rdeits** [jverzani/SymPy.jl#64]
Unfortunately, the current master branch of Julia v0.5 breaks SymPy by removing the ability to overload `Base.call` for abstract types. Attempting to use SymPy in 0.5 fails with:

```
ERROR: LoadError: LoadError: cannot add methods to an abstract type
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:267
 [inlined code] from ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /Users/rdeits/.julia/v0.5/SymPy/src/subs.jl, in expression starting on line 105
while loading /Users/rdeits/.julia/v0.5/SymPy/src/SymPy.jl, in expression starting on line 148
```

This regression is being discussed in https://github.com/JuliaLang/julia/issues/14919 

The trivial fix is to remove the call overloading entirely, but that seems like a poor solution. One might imagine that the issue could be resolved by replacing:

```julia
Base.call(ex::SymbolicObject, x::Dict) = subs(ex, x)
```

with

```julia
Base.call{T <: SymbolicObject}(ex::T, x::Dict) = subs(ex, x)
```

but this currently fails with 

```
ERROR: LoadError: LoadError: function type in method definition is not a type
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in include(::ASCIIString) at ./boot.jl:264
 in include_from_node1(::ASCIIString) at ./loading.jl:417
 in eval(::Module, ::Any) at ./boot.jl:267
 [inlined code] from ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
```

as discussed in https://github.com/JuliaLang/julia/issues/15317

If this is a big deal for you, you might want to consider making noise over at https://github.com/JuliaLang/julia/issues/14919 since there may still be time to fix this before everything is settled.

**Comment by jverzani** [comment]
Thanks for the heads up!!

**Comment by jverzani** [comment]
Checking, I added some code in `call.jl` to address this. I don't have an easy way to test, but does that solution work?

**Comment by rdeits** [comment]
Yup, looks like SymPy master is working! It still throws a few deprecation warnings, but it loads without error: 

```
julia> using SymPy
INFO: Recompiling stale cache file /Users/rdeits/.julia/lib/v0.5/SymPy.ji for module SymPy.
WARNING: Method definition latex(SymPy.SymbolicObject, Any...) in module SymPy at /Users/rdeits/.julia/v0.5/SymPy/src/display.jl:17 overwritten at /Users/rdeits/.julia/v0.5/SymPy/src/display.jl:44.
WARNING: Method definition #latex(Array, SymPy.#latex, SymPy.SymbolicObject, Any...) in module SymPy overwritten.
WARNING: Method definition expand(SymPy.Sym, Any...) in module SymPy at /Users/rdeits/.julia/v0.5/SymPy/src/poly.jl:122 overwritten at /Users/rdeits/.julia/v0.5/SymPy/src/SymPy.jl:208.
WARNING: Method definition #expand(Array, Base.#expand, SymPy.Sym, Any...) in module SymPy overwritten.
WARNING: Method definition require(Symbol) in module Base at loading.jl:308 overwritten at /Users/rdeits/.julia/v0.5/Requires/src/hook.jl:17.
```

**Comment by jverzani** [comment]
Thanks. I just added something to take care of the require issues, but didn't know of the others. I'll try and fix those and push the change to METADATA.

**Comment by rdeits** [comment]
Ok, glad I could help.

**Comment by jverzani** [comment]
I tagged a new version with this change and others. Hopefully it works now on v0.5 (though the travis tests are now failing, but I'm pretty sure that sits with PyCall not here).
