### ISSUE TITLE
LaTeX pretty print color with dark themes

### ISSUE THREAD

**Issue by jagot** [jverzani/SymPy.jl#65]
I use a dark theme ([Zenburn](https://pypi.python.org/simple/pygments-zenburn/)), but I can't seem to set the color of LaTeX rendered equations to something that stands out against the dark background.

I tried to follow [this post](http://stackoverflow.com/a/18260452), but it does not work:
![screenshot_20160307_132429](https://cloud.githubusercontent.com/assets/117947/13569453/719e36da-e468-11e5-87ee-d65945643268.png)

Any ideas on how to solve this?

The syntax coloring error due to the transpose operator is a separate issue.

**Comment by jverzani** [comment]
Boy, this seems like something in the repl code for handling the 'text/latex' mime type. I'm not familar with the customizations there. The thing you tried is for sympy's printing, which isn't respected here. Digging a bit, my guess is that this gets called:

```
writemime(io::IO, ::MIME"text/latex", x::Sym) = print(io, latex(x, mode="equation*", itex=true))
```

Maybe modifying that print statement will work? You could try somethings and report back.

**Comment by jagot** [comment]
I did a little bit of digging, and it goes all the way back in the to Jupyter/IPython code, specifically latex_to_png_dvipng in [latextools.py](https://github.com/ipython/ipython/blob/23b082fe0a89d5431633426fff1db958195b93cb/IPython/lib/latextools.py#L118). I'll have a look if I can do something there instead.

**Comment by jverzani** [comment]
Boy, that is way back. I would have thought that if this sits in Jupyter it would be a css thing with mathjax, not png. Anyways, good luck. I hope you figure something out.
