### ISSUE TITLE
invalid method name

### ISSUE THREAD

**Issue by Roger-luo** [jverzani/SymPy.jl#68]
I installed SymPy , but I got this:

```
julia> using SymPy
INFO: Precompiling module SymPy...
INFO: Recompiling stale cache file /home/roger/.julia/lib/v0.5/PyCall.ji for module PyCall.
ERROR: LoadError: LoadError: LoadError: syntax: invalid method name "ex::Sym"
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:392
 [inlined code] from boot.jl:263
 in anonymous at no file:0
 in eval at ./boot.jl:263
 [inlined code] from ./sysimg.jl:14
 in process_options at ./client.jl:254
 in _start at ./client.jl:377
while loading /home/roger/.julia/v0.5/SymPy/src/call.jl, in expression starting on line 8
while loading /home/roger/.julia/v0.5/SymPy/src/subs.jl, in expression starting on line 104
while loading /home/roger/.julia/v0.5/SymPy/src/SymPy.jl, in expression starting on line 147
ERROR: Failed to precompile SymPy to /home/roger/.julia/lib/v0.5/SymPy.ji
 in error at ./error.jl:21
 in compilecache at loading.jl:471
 in require at ./loading.jl:339
 in eval at ./boot.jl:263
```

The my Julia version is : 
julia> versioninfo()
Julia Version 0.5.0-dev+1491
Commit 41fb1ba (2015-11-27 16:54 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Is there anything wrong on my machine?

It seems that the definition for this function in v0.5dev is not valid?

```julia
function (ex::Sym)(args...)
    xs = free_symbols(ex)
    subs(ex, collect(zip(xs, args))...)
end
(ex::Sym)(x::Dict) = subs(ex, x)
(ex::Sym)(x::Pair...) = subs(ex, x...)
```

Best,

**Comment by jverzani** [comment]
Hmm, I'll have to check. It was working under the development version earlier, but I stopped checking when PyCall started failing. Thanks for the heads up. Hopefully, I'll get something fixed soon.

**Comment by jverzani** [comment]
Does it work now if you checkout the master branch, `Pkg.checkout("SymPy", "master")`?

**Comment by Roger-luo** [comment]
Still not work. And still the same error. Is this a new grammar in Julia? I didn't know that there are other types can be used like an operator?

**Comment by jverzani** [comment]
This is an attempt to work around changes in master related to calling of abstract types. It would require a relatively recent master (last month or so?). Are you using that?

**Comment by Roger-luo** [comment]
I deleted the package in my machine and clone the master branch on github. Is it correct?

**Comment by jverzani** [comment]
You can just do `Pkg.checkout("SymPy", "master")`. No need to delete the package. The command `Pkg.free` will restore to the usual version

**Comment by Roger-luo** [comment]
Yes, it just works fine at present :-). But actually I got this warning which made it fail to be built.

```
julia> using SymPy
WARNING: get_bigfloat_precision() is deprecated, use precision(BigFloat) instead.
 [inlined code] from ./error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 in get_bigfloat_precision() at ./deprecated.jl:50
 in mpmath_init() at /home/roger/.julia/v0.5/PyCall/src/conversions.jl:610
 in init_mpmath() at /home/roger/.julia/v0.5/SymPy/src/mpmath.jl:43
 in __init__() at /home/roger/.julia/v0.5/SymPy/src/SymPy.jl:315
 in _require_from_serialized(::Int64, ::Symbol, ::ASCIIString, ::Bool) at ./loading.jl:165
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:193
 in require(::Symbol) at ./loading.jl:323
 in eval(::Module, ::Any) at ./boot.jl:237
while loading no file, in expression starting on line 0
```

After I correct this deprecated function, and somehow everything works fine...

I've made a PR to PyCall... https://github.com/stevengj/PyCall.jl/pull/257

**Comment by jverzani** [comment]
Glad it is working now. That is just a warning, it shouldn't make things fail. Thanks for the heads up about this.
