### ISSUE TITLE
LoadError: Failed to precompile SymPy 

### ISSUE THREAD

**Issue by OrangeEfficiency** [jverzani/SymPy.jl#69]
I have encountered this issue when trying to use the latest Sympy.
```
using SymPy
INFO: Precompiling module SymPy...
INFO: Recompiling stale cache file C:\Users\OE\.julia\lib\v0.4\PyCall.ji for module PyCall.
ERROR: LoadError: LoadError: UndefVarError: computeY not defined
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading C:\Users\OE\.julia\v0.4\SymPy\src\plot-v4.jl, in expression starting on line 453
while loading C:\Users\OE\.julia\v0.4\SymPy\src\SymPy.jl, in expression starting on line 170
LoadError: Failed to precompile SymPy to C:\Users\OE\.julia\lib\v0.4\SymPy.ji
while loading In[6], in expression starting on line 1

 in error at error.jl:21

```
Would you mind helping me out ?

**Comment by angusmoore** [comment]
I have the same issue, pops up in julia 0.4.5, with SymPy 0.2.39 and Plots 0.5.4.

I assume that commit ec605cff35264b3014609c3a238a4810cb31a6f7 is designed to fix this, but switching SymPy over to master doesn't seem to fix the issue for me.

As a temporary fix, rolling Plots back to v0.5.3 worked for me.

**Comment by OrangeEfficiency** [comment]
I have tried switching SymPy over to master branch. It doesn't work for me either. :(

**Comment by jverzani** [comment]
Sorry, it is a `Plots.jl` issue, stemming from a rename. I'll see what I can do to fix.

**Comment by jverzani** [comment]
Can you check that 0eda26fbbdfb2b48fd2d2df36c9841dd2578719b addresses this?

If not, you may need to update Plots through `Pkg.update`.  There are some renaming efforts underway in that package (and more on the way) that I have been trying to keep up with.

**Comment by OrangeEfficiency** [comment]
Hi, thanks for your reply. Unfortunately, it doesn't seem to work. I keep getting this message when trying to run https://github.com/jverzani/SymPy.jl/commit/0eda26fbbdfb2b48fd2d2df36c9841dd2578719b
```
LoadError: UndefVarError: Sym not defined
while loading In[7], in expression starting on line 433
```

**Comment by angusmoore** [comment]
Yes, all that renaming in plots has really thrown a spanner in the works.

I've _quickly_ thrown together a new plots_v0-5-4.jl to reflect the new naming. With that change, I can get SymPy to compile on my install of julia (linux, 0.4.5), but I haven't tested the actual plotting functions because my julia install is on a remote computer via SSH and so doesn't have a plotting backend. Sorry! But I hope the renaming is at least a little helpful.

**Comment by jverzani** [comment]
Many thanks. I'll check this out next thing. There are even more changes coming to plots in master. This file (https://github.com/jverzani/SymEngineExtras.jl/blob/master/src/plots.jl) should mostly work with SymPy too.

**Comment by OrangeEfficiency** [comment]
I have switched it over to master branch. SymPy is working fine now. Thanks a lot for your help. Cheers :)

**Comment by tbreloff** [comment]
I just saw this after https://groups.google.com/forum/?hl=en#!topic/julia-users/ucnTm4NsRpo.  Someone should have pinged me!  Sorry for the inconvenience... have you fixed the issues on the master branch already?

**Comment by tbreloff** [comment]
Also... there is seemingly a LOT of redundant code related to plotting, as well as some Plots integration which might not be as clean/robust as it should be.  If you'd consider a redesign at some point let me know and I can advise some good ways to clean it up.

Also I noticed a comment in the code:

> ```
## quiver http://matplotlib.org/examples/pylab_examples/quiver_demo.html
## We add a plot of vectors (vectorplot). Hopefully this will be in `Plots` one
## day
```

See: https://github.com/tbreloff/Plots.jl/issues/178 and https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/quiver.ipynb

**Comment by jverzani** [comment]
@tbreloff I think I'm doing something wrong here and what used to work isn't anymore. My goal is to extend the interface of plots where a function works to a symbolic expression. With that in mind, I've extended these methods which have signatures for Function or FuncOrFuncs to a similar thing for symbolic expressions:

* `convertToAnyVector`
* `build_series_args`. When this was `createKWargs` it all worked, but now I can't get my modifications to get picked up. I also tried extending `process_inputs`, but this isn't working.

Have I been going about this all wrong?

**Comment by jverzani** [comment]
I'd be all ears. (I also saw the quiver part and am waiting for the next
tagged release)

On Mon, Apr 11, 2016 at 9:05 AM, Tom Breloff <notifications@github.com>
wrote:

> Also... there is seemingly a LOT of redundant code related to plotting, as
> well as some Plots integration which might not be as clean/robust as it
> should be. If you'd consider a redesign at some point let me know and I can
> advise some good ways to clean it up.
>
> Also I noticed a comment in the code:
>
> ## quiver http://matplotlib.org/examples/pylab_examples/quiver_demo.html
> ## We add a plot of vectors (vectorplot). Hopefully this will be in `Plots` one
> ## day
>
> See: tbreloff/Plots.jl#178
> <https://github.com/tbreloff/Plots.jl/issues/178> and
> https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/quiver.ipynb
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208330747>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
> Have I been going about this all wrong?

Maybe?  I need to review your code a little more before I can say for sure.  If you could give me a list of features that you want, I'm happy to help redesign from scratch.  Should we start a new issue to discuss design?

**Comment by jverzani** [comment]
My goal is to extend the Plots interface so that where it can take a
function `f`, it can take a symbolic expression as well. From there, all I
want to do is pass to the original a function created from the expression.
Something like this was working when `createKWargs` was called, but this
doesn't get called now.

```
function Plots.build_series_args(plt::Plots.Plot, f::SymOrSyms, xmin::Real,
xmax::Real; kw...)
    build_series_args(plt, lambidfy(f), xmin, xmax; kw...)
end
```

I think the right place to make this change is `process_inputs`? Or maybe
this whole approach is wrong.


On Mon, Apr 11, 2016 at 9:10 AM, Tom Breloff <notifications@github.com>
wrote:

> Have I been going about this all wrong?
>
> Maybe? I need to review your code a little more before I can say for sure.
> If you could give me a list of features that you want, I'm happy to help
> redesign from scratch. Should we start a new issue to discuss design?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208332209>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
Can you give me a small, self contained example of a `SymOrSyms` object and the resulting plot that you would expect?  I'll generate an implementation and we can discuss the pros/cons.

If it's a drop-in replacement of a function, then it certainly seems like you're expending too much energy here.

**Comment by jverzani** [comment]
The SymOrSyms object is a typealias:

typealias SymOrSyms @compat(Union{Sym, Plots.AVec{Sym}})

Where Sym is the type for a symbolic object. If ex is of Sym type, then
lambdify(ex) will be a function. So I just want to replace ex with
lambdify(ex) and pass along to the plot function.

So something like:

plot(x, 0, 1) will basically be a call to plot(lambdify(x), 0, 1).

Some more examples are here:
https://github.com/jverzani/SymPy.jl/blob/master/test/test-plots.jl

Thanks for any pointers!

On Mon, Apr 11, 2016 at 9:37 AM, Tom Breloff <notifications@github.com>
wrote:

> Can you give me a small, self contained example of a SymOrSyms object and
> the resulting plot that you would expect? I'll generate an implementation
> and we can discuss the pros/cons.
>
> If it's a drop-in replacement of a function, then it certainly seems like
> you're expending too much energy here.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208347299>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
I made a notebook to describe one possible method: https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/apply_recipe.ipynb

In a nutshell you would implement 2 functions (and nothing else):

```julia
function Plots._apply_recipe(d::Plots.KW, s::Sym, args...; kw...)
    (lambdify(s), args...)
end
function Plots._apply_recipe(d::Plots.KW, v::AbstractVector{Sym}, args...; kw...)
    (map(lambdify, v), args...)
end
```

This is certainly the easiest way to do it, if `Sym` is really a drop-in replacement for a function.  If you need more complexity, there are other options we can discuss... just give me an example to work with and I'll help.

**Comment by jverzani** [comment]
This mostly works! Awesome. The interface for parametric plots doesn't
though.

plot(x->sin(x), x->cos(x), 0, pi) works, but not plot(sin(x), cos(x), 0, pi)

Is there maybe just one more definition I need?



On Mon, Apr 11, 2016 at 10:20 AM, Tom Breloff <notifications@github.com>
wrote:

> I made a notebook to describe one possible method:
> https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/apply_recipe.ipynb
>
> In a nutshell you would implement 2 functions (and nothing else):
>
> function Plots._apply_recipe(d::Plots.KW, s::Sym, args...; kw...)
>     (lambdify(s), args...)endfunction Plots._apply_recipe(d::Plots.KW, v::AbstractVector{Sym}, args...; kw...)
>     (map(lambdify, v), args...)end
>
> This is certainly the easiest way to do it, if Sym is really a drop-in
> replacement for a function. If you need more complexity, there are other
> options we can discuss... just give me an example to work with and I'll
> help.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208370186>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
What is `x` in this example?  A `Sym`?  Is `sin(x)` another type?

**Comment by jverzani** [comment]
Yes, sorry and so sin(x) is also of type Sym.

On Mon, Apr 11, 2016 at 11:14 AM, Tom Breloff <notifications@github.com>
wrote:

> What is x in this example? A Sym? Is sin(x) another type?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208396319>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
Look at the example notebook again.  You would add an `_apply_recipe` definition for each signature.

**Comment by jverzani** [comment]
Great. I missed those. Now, one last request, contour plots and surfaces.

This works:

plot(linspace(-5,5,25), linspace(-5,5,25), (x,y) -> x^2 - y^2,
linetype=:contour)


but not


plot(linspace(-5,5,25), linspace(-5,5,25), x^2 - y^2, linetype=:contour)


when `x` and `y` are Sym objects. Is there a recipe there.


As well,


Surface((x,y) -> x^2 + y^2, 0:10, 0:10) works, but not


Surface(x^2 + y^2, x, y)


is there a similar recipe for this?


THanks so much for all the help

On Mon, Apr 11, 2016 at 11:18 AM, Tom Breloff <notifications@github.com>
wrote:

> Look at the example notebook again. You would add an _apply_recipe
> definition for each signature.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208398116>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by tbreloff** [comment]
If you look at the notebook again, I cleaned up a bit and added examples for contour/surface.  You should be able to copy the example and use `Sym` instead of `F`, and do the `lambdify` call.  This should get you most of the way there... let me know what else is missing.

**Comment by jverzani** [comment]
This is great. Thanks so much for your help here and for all your work on
the Plots package!

On Mon, Apr 11, 2016 at 12:13 PM, Tom Breloff <notifications@github.com>
wrote:

> If you look at the notebook again, I cleaned up a bit and added examples
> for contour/surface. You should be able to copy the example and use Sym
> instead of F, and do the lambdify call. This should get you most of the
> way there... let me know what else is missing.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208430143>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Thanks to @tbreloff for all his efforts here. This commit d2f08e9d35f1fa84cfb5dc9427a31a4b19d51996 not only works, but streamlines the code considerably. I'll tag a version soon.

**Comment by KristofferC** [comment]
"103 additions and 2,419 deletions.". wow

**Comment by tbreloff** [comment]
Heh... so much code cleanup makes me a happy man. :+1:

**Comment by jverzani** [comment]
As Tom pointed out earlier, there was a huge amount of code duplication.
But certainly lot s of real reduction and with luck, even more forthcoming.

On Mon, Apr 11, 2016 at 4:46 PM, Tom Breloff <notifications@github.com>
wrote:

> Heh... so much code cleanup makes me a happy man. [image: :+1:]
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/SymPy.jl/issues/69#issuecomment-208555053>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu
