### ISSUE TITLE
Log(base, x) not working

### ISSUE THREAD

**Issue by SoYman** [jverzani/SymPy.jl#71]
The Log function with an arbitrary base doesn't seem to work. 
calling `log(Sym(10), Sym(10))` returns the following error:
```
LoadError: MethodError: `call` has no method matching call(::Symbol, ::SymPy.Sym, ::SymPy.Sym)
Closest candidates are:
  BoundsError(!Matched::Any...)
  TypeVar(!Matched::Any...)
  TypeConstructor(!Matched::Any...)
  ...
while loading In[ ], in expression starting on line 1

 in log at C:\Users\*user*\.julia\v0.4\SymPy\src\math.jl:31
 in log at math.jl:102
```

One can obviously work around this by manually overriding with a function that divides Log(x)/Log(base) but that isn't particularly elegant.

**Comment by jverzani** [comment]
Thanks for the heads up!
