### ISSUE TITLE
Precompilation issue

### ISSUE THREAD

**Issue by ViralBShah** [jverzani/SymPy.jl#75]
On 0.4, I get a SymPy module precompilation error:

````
INFO: Precompiling module SymPy...
INFO: Recompiling stale cache file /Users/viral/.julia/lib/v0.4/SymPy.ji for module SymPy.
WARNING: Module SHA uuid did not match cache file
  This is likely because module SHA does not support  precompilation but is imported by a module that does.
````

**Comment by jverzani** [comment]
Thanks! I think this is something with PyCall (https://github.com/stevengj/PyCall.jl/issues/280) due to some change in the past 2 weeks, though your error message is different from the one I'm seeing.

**Comment by jverzani** [comment]
Fixed now on the PyCall side
