### ISSUE TITLE
Spice up @syms

### ISSUE THREAD

**Issue by alhirzel** [jverzani/SymPy.jl#76]
I have made a spiced-up version of the syms macro that includes a bunch of features I always wanted in MATLAB. It is backwards-compatible and adds:

1. support for named variables using `sym => "name"`
2. support for specifying assumptions like `positive=true`

Note that it is whitespace-insensitive owing to the magic of Julia's parser. Here is an example of usage of this macro:

    @syms2   Ld=>"L_d" Lq=>"L_q"  positive=true     a b c  FLd => "\lambda_d"  FLq => "\lambda_q"  real = true
    solve(Ld*Lq+1,Ld)
    solve(Ld*Lq-1,Ld)

In the above example, the variables Ld and Lq are real and positive, and a/b/c and FLd/FLq are real. (That is to say, assumption(s) apply to all terms to their left(s)). Here is the macro:

    macro syms2(x...)
        q = Expr(:block)
        as = []    # running list of assumptions to be applied
        ss = []    # running list of symbols created
        for s in reverse(x)
            if isa(s, Expr)    # either an assumption or a named variable
                if s.head == :(=)
                    s.head = :kw
                    push!(as, s)
                elseif s.head == :(=>)
                    push!(ss, s.args[1])
                    push!(q.args, Expr(:(=), s.args[1], Expr(:call, :symbols, s.args[2], as...)))
                end
            elseif isa(s, Symbol)   # raw symbol to be created
                push!(ss, s)
                push!(q.args, Expr(:(=), s, Expr(:call, :symbols, Expr(:quote, s), as...)))
            else
                throw(AssertionError("@syms expected a list of symbols and assumptions"))
            end
        end
        push!(q.args, Expr(:tuple, ss...)) # return all of the symbols we created
        eval(Main, q)
    end

**Comment by alhirzel** [comment]
Same thing but for SymFunctions:

    macro funs(x...)
        q = Expr(:block)
        fs = []    # running list of functions created
        for s in x
            if isa(s, Expr) && s.head == :(=>) # named function
                push!(fs, s.args[1])
                push!(q.args, Expr(:(=), s.args[1], Expr(:call, :SymFunction, s.args[2])))
            elseif isa(s, Symbol)
                push!(fs, s)
                push!(q.args, Expr(:(=), s, Expr(:call, :SymFunction, string(s))))
            else
                throw(AssertionError("@fns expected a list of symbols"))
            end
        end
        push!(q.args, Expr(:tuple, fs...)) # return all of the functions we created
        eval(Main, q)
    end

Another bit of test code for the pair of macros:

    @funs Vd Vq id iq
    @syms2 Rs Lq Ld FLq FLd We Wm Np FLf t

    basicDQEquations = [
        -Vq(t) + Rs*iq(t) + We*Ld*id(t) + We*FLf + Lq*iq'(t)
        -Vd(t) + Rs*id(t) - We*Lq*iq(t) + Ld*id'(t) ]

**Comment by jverzani** [comment]
This is great! Thanks so much. Will be checking in the additions soon. I renamed `@funs` to `@symfuns` as that seemed more natural.

**Comment by jverzani** [comment]
Closing with 5938ee4ea36c36e77250304a640649034cf91651
