### ISSUE TITLE
SymFunction with multiple variables not working

### ISSUE THREAD

**Issue by helo9** [jverzani/SymPy.jl#81]
in python's sympy this is working:
```
import sympy

x,y = sympy.symbols('x, y')
f = sympy.Function('w')
f(x,y)
```
while in SymPy on JuliaBox (0.4.6), SymPy (0.3.1) reports an error

```
using SymPy

x,y = Sym('x, y')

f = SymFunction('w')
f(x,y)
```

> LoadError: MethodError: `free_symbols` has no method matching free_symbols(::SymPy.SymFunction)
while loading In[45], in expression starting on line 1
 in call at /opt/julia_packages/.julia/v0.4/SymPy/src/call-0.4.jl:10

**Comment by jverzani** [comment]
Thanks. I need to widen the signature. It only works for a single variable now.

**Comment by jverzani** [comment]
I just pushed a change to work on this. Can you test it out to see if it covers what you need? If not, please reopen. Thx.

**Comment by helo9** [comment]
juliabox seems to be offline, but it is working on my local machine
nice work, thanks
